# Generated by Django 5.0.4 on 2024-04-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('fecha_alta_sistema', models.DateField()),
                ('done_carroceria', models.BooleanField(default=False)),
                ('done_vidrios', models.BooleanField(default=False)),
                ('done_llantas', models.BooleanField(default=False)),
                ('done_interior', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateField()),
            ],
        ),
    ]
