# Generated by Django 5.0.4 on 2024-04-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_task_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='marca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='modelo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='responsable',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='sucursal',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
