# Generated by Django 5.0.4 on 2024-04-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_name_carmodel_model_carmodel_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbrand',
            old_name='name',
            new_name='brandname',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='brand',
            new_name='brandname',
        ),
    ]
