# Generated by Django 5.0.4 on 2024-04-30 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_task_done_remove_task_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='carbrand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myapp.carbrand'),
            preserve_default=False,
        ),
    ]
