# Generated by Django 5.0.4 on 2024-04-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_task_carbrand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='vin',
        ),
    ]
