# Generated by Django 5.0.4 on 2024-04-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_title_task_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='origin',
        ),
    ]
