# Generated by Django 5.0.4 on 2024-04-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_task_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='chassis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='upholstery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='wheels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='windows',
            field=models.BooleanField(default=False),
        ),
    ]
