# Generated by Django 5.0.4 on 2024-05-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_task_chassis_task_upholstery_task_wheels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datecompleted_client_approval',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='datecompleted_history',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='datecompleted_manager_approval',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
