# Generated by Django 5.0.4 on 2024-05-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_task_datecompleted_client_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='carimage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
