# Generated by Django 5.0.4 on 2024-05-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_task_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deniedbyclient',
            field=models.BooleanField(default=False),
        ),
    ]
