# Generated by Django 5.0.4 on 2024-05-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_task_deniedbyclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AddField(
            model_name='task',
            name='motivo_devolucion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ventanas'), (2, 'Carrocería'), (3, 'Llantas'), (4, 'Interior'), (5, 'Maletero')], null=True),
        ),
    ]
