# Generated by Django 5.0.4 on 2024-05-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_task_comment_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comment_client',
        ),
        migrations.RemoveField(
            model_name='task',
            name='motivo_devolucion',
        ),
        migrations.AddField(
            model_name='task',
            name='comentario_rechazo_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='comentario_rechazo_manager',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='motivo_rechazo_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='motivo_rechazo_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
