# Generated by Django 5.0.4 on 2024-05-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_task_comment_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoRechazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
