# Generated by Django 5.0.4 on 2024-05-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_task_motivo_rechazo_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='motivo_rechazo_cliente',
            field=models.CharField(blank=True, choices=[('CR', 'Cristales'), ('LL', 'Llantas'), ('CA', 'Carrocería'), ('MA', 'Maletero'), ('IN', 'Interior'), ('AL', 'Alfombrillas'), ('SA', 'Salpicadero'), ('TA', 'Tapicería'), ('OT', 'Otro')], max_length=2, null=True),
        ),
    ]
