# Generated by Django 5.0.4 on 2024-05-14 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_changelog_changereason_alter_changelog_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.task')),
            ],
        ),
    ]
